### PR TITLE
Localized tool tips + minor layout tweak

### PR DESCRIPTION
**Pull request by humdingerb**

### CODE REVIEW

**Comment by humdingerb** [comment]
If you guys don't have immediate string changes/additions, I'll update the translations at Polyglot this weekend.

**Comment by jackburton79** [comment]
@nexus6-haiku is working on adding rename symbol support to OutlineView and will probably add a couple of strings

**Comment by nexus6-haiku** [comment]
Does it make sense? The tooltips map to language keywords: class, structure, enum, interface, etc.
This applies especially to C++ and C#, and Python to some extent.

**Comment by jackburton79** [comment]
> Does it make sense? The tooltips map to language keywords: class, structure, enum, interface, etc. This applies especially to C++ and C#, and Python to some extent.

I think we should follow what popular IDEs (vsCode, Eclipse, etc) do.

**Comment by jackburton79** [comment]
@humdingerb I'd apply the layout fixes only, for now

**Comment by nexus6-haiku** [comment]
Mine was a genuine question. I only use them in English but I've double checked and Visual Studio Code actually translates these terms.
As things stand, we can keep the translations

**Comment by jackburton79** [comment]
> Mine was a genuine question. 

Of course, mine was too :-)

**Comment by humdingerb** [comment]
Yes, the possibility to have those terms translated is good to be kept. Even if for the languages we know, it may stay untranslated,  there may be other languages/cultures that do.

**Pull request merged**
