### PR TITLE
Added some documentation, Help menu item

### PR DESCRIPTION
**Pull request by humdingerb**
This is more like a quick Get Started document. It can be extended over time. A navigation bar at the top has been commented out for now.

Updated en.catkeys

### CODE REVIEW

**Comment by humdingerb** [comment]
The updated "Help" string in the catkeys should be easily translatable via Polyglot's "Pre-translate". Otherwise, there are enough applications that have a "Help" we can get the translations from.
As soon as it's updated at Polyglot, I can take care of that.

This is more QuickStart than complete documentation. It should be extended in the future. However, an IDE being targetted at the very tech savvy, I don't think every detail has to be described. As a part time hobby coder, I had few problems figuring out the basics.

**Comment by jackburton79** [comment]
Thanks for this huge work!
We're planning to release... TODAY! And we'd like to include this. I'm just starting to skim through the PR. Do this PR also need to change the Haikuports recipe, by chance ?

**Comment by humdingerb** [comment]
Should we point to https://github.com/Genio-The-Haiku-IDE/Genio/discussions for people to post their questions/difficulties ?
Then we may get some input where people are struggling and put these topics in the docs.

**Comment by jackburton79** [comment]
> Should we point to https://github.com/Genio-The-Haiku-IDE/Genio/discussions for people to post their questions/difficulties ? Then we may get some input where people are struggling and put these topics in the docs.

Yes, definitely!

**Comment by humdingerb** [comment]
Oh, I cut it close... :)

The recipe has to be changed only a little. Instead of the "ReadMe.md" the contents of the new "documentation" folder needs to be copied to $docsDir.

I'll add the link to "discussions" in a second.

**Comment by humdingerb** [comment]
Link to "Discussions" added.

**Comment by jackburton79** [comment]
> Oh, I cut it close... :)

Even closer than you think.

> The recipe has to be changed only a little. Instead of the "ReadMe.md" the contents of the new "documentation" folder needs to be copied to $docsDir.

This is the current recipe:

```
SUMMARY="The Haiku IDE"
DESCRIPTION="Genio is a native IDE for the Haiku operating system. \
It has a rich editor supporting syntax highlighting, auto completion and other advanced features. \
It contains a set of templates to quickly develop and build your projects."
HOMEPAGE="https://github.com/Genio-The-Haiku-IDE/Genio/releases"
COPYRIGHT="2022-2024 The Genio Team"
LICENSE="BSD (3-clause)
	MIT"
REVISION="1"
SOURCE_URI="https://github.com/Genio-The-Haiku-IDE/Genio/archive/v2.1.tar.gz"
CHECKSUM_SHA256="97e46dd5523702a4c7d91c68aee7806d4acab9a7b4b58fe4756429d00c101ffc"
SOURCE_FILENAME="Genio-v2.1.tar.gz"
SOURCE_DIR="Genio-2.1"

ARCHITECTURES="all !x86_gcc2"
SECONDARY_ARCHITECTURES="x86"

PROVIDES="
	genio${secondaryArchSuffix} = $portVersion
	app:Genio = $portVersion
	"
REQUIRES="
	haiku${secondaryArchSuffix}
	gcc${secondaryArchSuffix}_syslibs_devel
	llvm17${secondaryArchSuffix}_clang
	lib:liblexilla$secondaryArchSuffix >= 5.2.4
	lib:libgit2$secondaryArchSuffix
	lib:libyaml_cpp$secondaryArchSuffix
	"

BUILD_REQUIRES="
	haiku${secondaryArchSuffix}_devel
	devel:liblexilla$secondaryArchSuffix >= 5.2.4
	devel:libgit2$secondaryArchSuffix >= 1.5
	devel:libyaml_cpp$secondaryArchSuffix >= 0.8
	"
BUILD_PREREQUIRES="
	makefile_engine
	cmd:gcc$secondaryArchSuffix
	cmd:make
	"

BUILD()
{
	make OBJ_DIR=objects \
		BUILDHOME=`finddir B_SYSTEM_DEVELOP_DIRECTORY` \
		$jobArgs
	make bindcatalogs OBJ_DIR=objects \
		BUILDHOME=`finddir B_SYSTEM_DEVELOP_DIRECTORY`
}

INSTALL()
{
	install -m 0755 -d "$appsDir/Genio"
	install -m 0755 -t "$appsDir/Genio/" app/Genio
	cp -a data "$appsDir/Genio/"

	install -m 0755 -d "$docDir"
	install -m 0644 -t "$docDir" Readme.md

	addAppDeskbarSymlink $appsDir/Genio/Genio
}

```

So we need to change this:

```
install -m 0755 -d "$docDir"
install -m 0644 -t "$docDir" Readme.md
```

with 

`cp -a documentation "$docDir"`

**Comment by humdingerb** [comment]
> cp -a documentation "$docDir"

I think it should be

cp -r documentation/* $docDir/

because we only want the files, not the "documentation" folder itself.

**Comment by humdingerb** [comment]
Sorry for the stress...

BTW, you can check the "Help" menu when copying the contents of "documentation" to `/boot/home/config/non-packaged/documentation/packages/genio/`

**Comment by jackburton79** [comment]
> Sorry for the stress...
> 
> BTW, you can check the "Help" menu when copying the contents of "documentation" to `/boot/home/config/non-packaged/documentation/packages/genio/`

I also added the option to load the documentation directly from the local repo folder (as a fallback)

**Comment by humdingerb** [comment]
Good.
BTW, I just noticed that the "Project settings" window has changed.
Should I try to adapt the docs?

**Comment by jackburton79** [comment]
> Good. BTW, I just noticed that the "Project settings" window has changed. Should I try to adapt the docs?

We've chosen not to include the updated project settings window in this release, so I'd say not yet.

**Comment by jackburton79** [comment]
> > cp -a documentation "$docDir"
> 
> I think it should be
> 
> cp -r documentation/* $docDir/
> 
> because we only want the files, not the "documentation" folder itself.

I think I'm doing something wrong, since building the package fails with 

"cp: target '/packages/genio-2.1.0-1/.self/documentation/packages/genio': No such file or directory"

Do I have to create the documentation directory in the recipe ?

**Comment by humdingerb** [comment]
Right. "Install" apparently does that for you...
So it's:

```
mkdir -p $docDir
cp -r documentation/* $docDir/
```

I completed the translations at Polyglot. Took the strings from other apps that also got a "Help" string.
Note, French is not at 100% because of the untranslated git commands. Those weren't marked as "translated". Shall I do that, just to not be confused in the future?

**Comment by humdingerb** [comment]
BTW, you may want to give a better sales itch in the recipe description. Maybe take some of the Readme.md, like:

```
Genio is a native and fully functional IDE for the Haiku.
Some of the features of the Genio IDE are:

*   LSP Server support (autocompletion, signature help, go to definition/implementation/declaration, quick fix, format)
*   Multi-project browser
*   Integrated source control with GIT (including opening a remote project)
*   Links to file and build errors in Build Log and Console I/O
*   Build on save / Save on build
*   User templates for quickly creating new files and projects
*   Rich editor with many features, like syntax highlighting
*   Full screen and Focus mode
```

**Comment by jackburton79** [comment]
> Right. "Install" apparently does that for you... So it's:
> 
> ```
> mkdir -p $docDir
> cp -r documentation/* $docDir/
> ```
> 
> I completed the translations at Polyglot. Took the strings from other apps that also got a "Help" string. Note, French is not at 100% because of the untranslated git commands. Those weren't marked as "translated". Shall I do that, just to not be confused in the future?

Yes, thanks!

**Comment by humdingerb** [comment]
Hmm, the French has those git commands translated (didn't check other languages). Not sure that's what French developers prefer. So I left those "Needs work"-yellow, because can then be changed more easily.

What do you think about asking on the Haiku forum what's preferred by our international devs?
I can do that, if you want.

Of course this would be too late for this release, but maybe the next.

**Comment by jackburton79** [comment]
> What do you think about asking on the Haiku forum what's preferred by our international devs? I can do that, if you want.

Would be great, thank you!

**Pull request merged**
