### PR TITLE
Extended documentation

### PR DESCRIPTION
**Pull request by humdingerb**
The "Settings" page is still empty, mainly because I'll wait until the possible changes to the "Project settings" window are finished.

Take your time looking through it all and comment with any additions or corrections you may want to add. Maybe check out this PR and read it in the browser, probably better than seeing the html code as a diff on github...

The "Editor" page is probably the most 'useful' page, describing how to effectively work with Genio. Feel free to propose more tips&tricks.

For the "Menu" page, the "Edit|Format" item lacks an explanation, because I don't know exactly what it's supposed to do, or it doesn't work yet...

### CODE REVIEW

**Comment by jackburton79** [comment]
Nice work!

> For the "Menu" page, the "Edit|Format" item lacks an explanation, because I don't know exactly what it's supposed to do, or it doesn't work yet...

I think it formats the code according to... some style, but I think it's hardcoded

**Comment by Freaxed** [comment]
> Nice work!
> 
> > For the "Menu" page, the "Edit|Format" item lacks an explanation, because I don't know exactly what it's supposed to do, or it doesn't work yet...
> 
> I think it formats the code according to... some style, but I think it's hardcoded

Format is a LSP feature. By using clangd server you can configure a file called .clang-format to define your coding style. In Genio we have such file and is as much as possible compliant with the haiku coding style. It can't be 100% compliant and thats why we have this project (https://github.com/owenca/haiku-format) (and soon or later would be nice to include somhow in genio).

**Comment by humdingerb** [comment]
Oh, right, now I see it's working with the Genio project. I'm familiar with "haiku-format".
I created #291 with some thoughts on code style formatting.

**Comment by jackburton79** [comment]
Can we merge this work for now ?
Even if there are still missing pieces, it's already much more complete than the current one.

**Comment by jackburton79** [comment]
Hi Humdinger, can we merge this yet ?

**Comment by humdingerb** [comment]
Of course , anytime.

**Pull request merged**
