### PR TITLE
Line endings: Remove 'Set', keep 'Convert'

### PR DESCRIPTION
**Pull request by humdingerb**
As discussed at https://github.com/Genio-The-Haiku-IDE/Genio/discussions/87

### CODE REVIEW

**Comment by Freaxed** [comment]
Fine for me

**Comment by nexus6-haiku** [comment]
Fine by me, too

**Comment by Freaxed** [comment]
@humdingerb , do you mind resolving the conflict? looks easy but really don't know what value to put

**Comment by humdingerb** [comment]
There you go. Maybe we just shouldn't update the en.catkeys when strings get changed and wait until one of you guys decides to update the strings at Polyglot and have him explicitely do a 'make catkeys' before uploading it.

**Pull request merged**
