### PR TITLE
Docs: Add page on "Configuring Clangd / LSP"

### PR DESCRIPTION
**Pull request by humdingerb**
More or less imported 'Configuring-clangd-lsp.md' into the user documentation. Only removed the install instruction for llvm and syslibs, because those should come as dependencies of Genio, if I'm not mistaken.

### CODE REVIEW

**Comment by jackburton79** [comment]
We're considering removing the dependency on llvm/clang for the next release, since technically one could do python development and not need llvm at all, and install pylsp instead.

**Comment by humdingerb** [comment]
Oh, I see. Just added the package installing, too.

I suppose one needs to re-build compile_commands.json regularly?
Every time a source file is added/removed, Makefile changes... what else?
That info should be added to that page.

**Comment by jackburton79** [comment]
Every time you update the makefile (adding or removing source files) you should rebuild the compile db

**Comment by humdingerb** [comment]
Alright. I added a little info box pointing this out.

**Comment by humdingerb** [comment]
If you or your collegues don't have changes I should make, feel free to merge.

**Pull request merged**
