### PR TITLE
config manager creates only the storage provider needed (fix bug #310)

### PR DESCRIPTION
**Pull request by Freaxed**

### CODE REVIEW

**Comment by jackburton79** [comment]
I tested a bit, but doesn't seem to load the old settings correctly.
I compiled Genio v1, deleted the Genio settings folder, started Genio with empty settings. Changed some settings, closed Genio v1.
Then built and launched the version with this PR, but doesn't load the old settings, starts with defaults instead.

**Comment by Freaxed** [comment]
How the old version without the storage providers works? I don't think it could 'fail' if the "semantic format" of the config are different.. If a key is not available or in different format, the ConfigManager code just take the default. It fails only for technical reason (mostly file related errors). This fix just fails for the same reasons..

**Comment by jackburton79** [comment]
Sorry, you 're right. I tested loading Genio' s old settings, but that never worked. What should work is loading project settings from an older version, which I haven't tried yet.

**Comment by jackburton79** [comment]
Tried right now. It works. You can merge the pr

**Pull request merged**
