### PR TITLE
rdef: import icons as files

### PR DESCRIPTION
**Pull request by humdingerb**
Import the data directly from the icon files instead of dumping the hex data into the resource file. Makes possible changes in the future much easier.

### CODE REVIEW

**Comment by humdingerb** [comment]
Should be done with Spinner.rdef as well, but the icon files aren't (yet) in the repo. Does anyone still have those locally?

**Comment by nexus6-haiku** [comment]
Me neither! That's mind blowing...
We need to add this option to the import function.

**Comment by nexus6-haiku** [comment]
> Should be done with Spinner.rdef as well, but the icon files aren't (yet) in the repo. Does anyone still have those locally?

I think I have them somewhere.

**Comment by humdingerb** [comment]
Saw that some time ago in an rdef file in the Haku source. 
I also tried to have the paths in variables, but couldn't get it to work...

**Pull request merged**
