### PR TITLE
Added Changelog in AboutWindow

### PR DESCRIPTION
**Pull request by jackburton79**
This PR introduces a way to show ChangeLog into the about window.
There is a Changelog.txt file which needs to be updated on every release.
On every change, a Changelog.h file will be generated and included in the about window.

### CODE REVIEW

**Review by nexus6-haiku — COMMENTED** [review]
For my education: what is the benefit of an intermediate changelog.h?
Couldn't we ship a changelog.txt with the package (e.g. in data/changelog.txt) and display it?

**Comment by jackburton79** [comment]
> For my education: what is the benefit of an intermediate changelog.h? Couldn't we ship a changelog.txt with the package (e.g. in data/changelog.txt) and display it?

Yeah, that's also an option. The difference is that you open a file (which you need to supply) instead of having the strings in-code.

**Comment by Freaxed** [comment]
I'm ok with  .h file, looks much more solid :D. If possible, I would also like to include some information about git (revision and branch)

**Comment by jackburton79** [comment]
I realized that, if implemented this way, it can't be translated

**Comment by nexus6-haiku** [comment]
Do we really need it to be translated?

**Comment by Freaxed** [comment]
@jackburton79, @nexus6-haiku,  What is preventing this to be merged?

**Comment by jackburton79** [comment]
As I said, I realized that this implementation does not support translations. If it's ok for you I can merge It anyway After writing a real Changelog.txt and not an empty one

**Comment by Freaxed** [comment]
Ok, thank you for clarifying. I’m fine to merge it without the translation
support. About filling the Changelog.txt: if you prefer we can fill it
directly in the main branch.

Il giorno mar 6 giu 2023 alle 08:46 Stefano Ceccherini <
***@***.***> ha scritto:

**Comment by jackburton79** [comment]
> Ok, thank you for clarifying. I’m fine to merge it without the translation support. About filling the Changelog.txt: if you prefer we can fill it directly in the main branch.

Ok, will do

**Pull request merged**
