### PR TITLE
Project settings: Center project header as simple BStringView

### PR DESCRIPTION
**Pull request by humdingerb**
This is only an optical change in the end.

* Use a BStringView for the project header instead of a BBox.
* Center project header, use 1.2x larger font.
* Simplify the project "label" generation by removing unnecessary member variables.
* Rename saveButton to okButton and make default. Now ENTER will save settings and close the window.

### CODE REVIEW

**Comment by humdingerb** [comment]
I originally only wanted to center the project name in the settings.

Is a future plan that relies on it being a BBox and needing the member variables fProjectBoxLabel and fProjectBoxProjectLabel? Maybe I overlooked something?

**Comment by jackburton79** [comment]
We plan to convert the project settings to use the same class as the global settings, so it gets an auto generated config window. Of course, we'll need to extend or rewrite it a bit because project settings window could have different requirements

**Comment by jackburton79** [comment]
I haven't looked at your changes yet, but if they improve the look we could
apply them anyway, even if we'll change it later.

Il dom 24 dic 2023, 09:08 humdinger ***@***.***> ha scritto:

**Comment by humdingerb** [comment]
👍

**Pull request merged**
