### PR TITLE
Feature QuitAlert panel from Koder

### PR DESCRIPTION
**Pull request by Freaxed**
When it's requested to save more than one files, we now have the Koder QuitPanel to do it!
Code needed a bit of refactor to accomodate the change

### CODE REVIEW

**Comment by nexus6-haiku** [comment]
It's ok but there is a commit for the signature help that has already been committed previously

**Comment by Freaxed** [comment]
It looks like I consistently make some mistakes while switching from one branch to another.. :(

**Comment by nexus6-haiku** [comment]
Looks like Genio keeps a file opened with changes from the previous branch and carries them over to the new one inadvertently

**Comment by Freaxed** [comment]
Uhm, even if Genio keeps a file open it's impossibile to move a commit from one branch to another.. I'll take more care in branching and switching in the next PRs..

Are you happy to merge this?

**Comment by nexus6-haiku** [comment]
Please go ahead

**Pull request merged**
